### ISSUE TITLE
Could you clarify on the licensing of models and code 

### ISSUE THREAD

**Issue by papasanimohansrinivas** [xk-huang/segment-caption-anything#1]
Hi @xk-huang excellent work and can't thank enough , what is the stance of licensing of models and code here , need clarity here

**Comment by xk-huang** [comment]
Hi @papasanimohansrinivas, Thanks for pointing out the missing license!

The code and our trainable weights (i.e., the text query mixer), are udner The model is licensed under the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0). I would add the license ASAP.

Free free to reach out if you have any more questions.
