### ISSUE TITLE
Follow-up question about how to apply the custom dataset

### ISSUE THREAD

**Issue by AnnyShen55** [xk-huang/segment-caption-anything#10]
Hello, I've noticed you suggest the run function and the auto_generator.py, yet would you mind telling me where should i insert the run function in the auto_generator and/or where should i modify? Thank you!

**Comment by xk-huang** [comment]
Hi @AnnyShen55! Do you mean that you want to use the "anything-mode"? You can refer to https://github.com/xk-huang/segment-caption-anything/issues/6#issuecomment-2171497933

**Comment by AnnyShen55** [comment]
Right, I saw that reply, and yet I'm still not sure how to combine auto_generator.py and run function to apply the anything-mode? would you mind telling me how to achieve the anything-mode in details? Thank you!
