### ISSUE TITLE
Question for config file vg-dense-local

### ISSUE THREAD

**Issue by liweiyangv** [xk-huang/segment-caption-anything#13]
I'm sorry, here is a question for running the code. How to obtain the folder annotation and the file densecap_split.json

**Comment by xk-huang** [comment]
Please refer to: https://github.com/xk-huang/segment-caption-anything/blob/0d3f0b4a9caa8d5f8d23f5a301b9048161e930bc/src/data/data_scripts/visual_genome.py#L472-L475
