### ISSUE TITLE
parameters for gpt2-large for detail

### ISSUE THREAD

**Issue by liweiyangv** [xk-huang/segment-caption-anything#16]
Could you provide the parameters of the file for training the model with gpt2-large and sam-huge in detail? Thanks!

**Comment by xk-huang** [comment]
Please refer to the supplementary and the [amlt configs](https://github.com/xk-huang/segment-caption-anything/tree/main/amlt_configs). Note that the batch size has to be large enough to achieve the results in the paper.

**Comment by liweiyangv** [comment]
I have used bs=8 (per_device_train_batch_size=2 with 4 gpus), max_steps=20w for training, but only gets ciderd=130.04. These are the parameters I used. Could you please help me check if there are any issues? Thank you.




accelerate launch --config_file amlt_configs/accelerate_deepspeed_config.local.yaml train.py \
train_data='[vg-densecap-local]' eval_data='[vg-densecap-local]' \
+model=base_sca_multitask_v2 \
training.do_train=True \
training.do_eval=True \
training.do_inference=True \
training._n_gpu=4 \
+data.streaming=False \
training.max_eval_samples=100 \
training.max_steps=200000 \
training.fp16=True \
training.output_dir=exp_pretrain_finetune_wo_language_model_ori_pretrain_1e_4 \
training.output_log_dir=exp_pretrain_finetune_wo_language_model_ori_pretrain_1e_4\log \
model.cache_dir=.model.cache_try_trainable_bs8_gpu/ \
training.save_strategy=steps \
training.save_steps=5000 \
training.save_total_limit=3 \
training.optim=adamw_torch \
training.evaluate_before_train=True \
training.per_device_train_batch_size=2 \
training.evaluation_strategy=steps \
training.eval_steps=5000 \
training.logging_steps=1000 \
training.logging_first_step=True \
training.dataloader_num_workers=8 \
training.num_masks_per_sample=16 \
wandb.log=False \
model.num_caption_tokens=8 \
model.additional_num_hidden_layers=12 \
model.num_task_tokens=6 \
training.lr_scheduler_type=cosine \
model.lm_head_model_name_or_path=gpt2-large \
training.learning_rate=1e-4 \
training.weight_decay=1e-4 \
training.trainable_params='[mask_decoder.additional_transformer,mask_decoder.caption_tokens,task_tokens,language_project]' training.compute_metrics=null \
training.warmup_steps=200 \
training.warmup_ratio=0.33333333 \
training.compute_metrics=null

-----原始邮件-----
发件人: "Xiaoke Huang" ***@***.***>
发送时间: 2024-12-04 00:36:22 (星期三)
收件人: xk-huang/segment-caption-anything ***@***.***>
抄送: liweiyangxjtu ***@***.***>, Author ***@***.***>
主题: Re: [xk-huang/segment-caption-anything] parameters for gpt2-large for detail (Issue #16)


Please refer to supp and the amlt config. Btw, the batch size have to be large enough to achieve the results in the paper.
