### ISSUE TITLE
How could I try your gradio app?

### ISSUE THREAD

**Issue by xiahongchi** [xk-huang/segment-caption-anything#2]
Thanks for your great work!!!

Here I have some questions: What ckpt should I use to start your gradio app? Where should I download it from and how should I configure that?

![image](https://github.com/xk-huang/segment-caption-anything/assets/75728800/319f7196-b3f3-453a-85cc-5d43bd4defe3)

I tried leaving it blank, but got this error:

![image](https://github.com/xk-huang/segment-caption-anything/assets/75728800/298e5a14-5d42-466a-9fbb-76c62c62dd56)

And if I set it to "xk-huang/segment-caption-anything-gpt2_large-vg", it would also raise fault:

![image](https://github.com/xk-huang/segment-caption-anything/assets/75728800/af63ef40-8090-4771-9b85-aeac995651e8)

Thanks for your help!

**Comment by xk-huang** [comment]
Hi, @xiahongchi 

Here I will reply for your questions in points:

> What ckpt should I use to start your gradio app? Where should I download it from...

The checkpoints are hosted on HuggingFace Hub. Please click the link to download them.
- e.g., https://huggingface.co/xk-huang/segment-caption-anything-gpt2_large-pt

The performance and the download links are organized here:
- https://github.com/xk-huang/segment-caption-anything/blob/main/docs/MODEL_ZOO.md

> ... and how should I configure that?

There is no need to configure anything. The config file is in the checkpoint directory.

> I tried leaving it blank, but got this error:
> And if I set it to "xk-huang/segment-caption-anything-gpt2_large-vg", it would also raise fault:

After you download the checkpoints followed the links above. **Replace** `CKPT_PATH=` to `CKPT_PATH=xxx`, where `xxx` is the path to the checkpoint **directory**.

Hope these could help!

**Comment by xiahongchi** [comment]
Yes, now it works! Thanks!

**Comment by hamzafer** [comment]
"Hi @xiahongchi, could you please share the details about the setup and environment you use for running the Gradio app demo? Thanks!"
