### ISSUE TITLE
class labels

### ISSUE THREAD

**Issue by RohanChacko** [xk-huang/segment-caption-anything#3]
Hi, 

Thank you for sharing code. How can I use the model to generate class labels instead of captions? Thanks!

**Comment by xk-huang** [comment]
Hi, @RohanChacko 

The checkpoint for predicting class labels in Objects365 format is uploaded [here](https://github.com/xk-huang/segment-caption-anything/blob/main/docs/MODEL_ZOO.md):

> We also upload the ["Pretrain" weights](https://huggingface.co/xk-huang/segment-caption-anything-gpt2_large-pt/tree/main) for "SCA (GPT2-large, Pretrain+VG)".

Besides, I would like to refer you to https://github.com/RockeyCoss/Prompt-Segment-Anything which achieves similar results.
