### ISSUE TITLE
Where should I get "splits.json: from? when loading visual-genome dataset: FileNotFoundError("Couldn't find file at https://homes.cs.washington.edu/~ranjay/visualgenome/data/dataset/densecap_splits.json")

### ISSUE THREAD

**Issue by RobitsG** [xk-huang/segment-caption-anything#4]

**Comment by RobitsG** [comment]
edit visual_genome.py in line 477 with base_annotation_url = "https://raw.githubusercontent.com/jcjohnson/densecap/master/info"

**Comment by QingYunA** [comment]
Now you need to edit visual_genome.py in line 480:
```python
base_annotation_url = "https://raw.githubusercontent.com/ruotianluo/Faster-RCNN-Densecap-torch/master/info/"
```

**Comment by liweiyangv** [comment]
> edit visual_genome.py in line 477 with base_annotation_url = "https://raw.githubusercontent.com/jcjohnson/densecap/master/info"
Hello, i get this error, how can i deal with it, 
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url='https://raw.githubusercontent.com/jcjohnson/densecap/master/info/region_descriptions.json'
