### ISSUE TITLE
Running Inference on the Custom Dataset

### ISSUE THREAD

**Issue by Brian96086** [xk-huang/segment-caption-anything#6]
Hi, 
Thanks for the interesting and impressive work! I would like to run inference on a custom dataset. In the docs, running inference is involved with running train.py, which is strongly tied with the training setup. Do you have any suggestions or scripts so that I can run inference effectively and independently of training? 

Thanks again for your time and effort !

**Comment by xk-huang** [comment]
Hi @Brian96086,

There are two solutions to inference the models on the custom dataset.

1. The API of SCA model: https://github.com/xk-huang/segment-caption-anything/blob/ceaca8746695eb0cd0f16ddb9c8acff280f3fed0/scripts/apps/sca_app.py#L158

2. Prepare the dataset into VG/COCO format, and use scripts in https://github.com/xk-huang/benchmark-referring-vllm.

I would prefer the first one for the maximum flexibility.

**Comment by Brian96086** [comment]
Hi @xk-huang ,
Thanks for the clarification and instruction. Really appreciate your help!
