### ISSUE TITLE
Not able to run Gradio Demo

### ISSUE THREAD

**Issue by hamzafer** [xk-huang/segment-caption-anything#7]
#### Environment:
- **Operating System**: Windows
- **Hardware**: NVIDIA GPU with appropriate drivers and setup

#### Setup:
Due to compatibility issues with DeepSpeed on Windows, I've opted to use Docker for the environment setup. After configuring Docker and installing the necessary dependencies, I initiated a Gradio interface to interact with the model. However, I encountered several issues detailed below:

#### Issues Encountered:
1. **Port Accessibility**: Initially had difficulties accessing the Gradio interface through the specified port in Docker. This was temporarily resolved using Ngrok to expose the port.

2. **Performance and Warnings**: When accessing the application via Ngrok, the response times are exceedingly long, and several warning messages are logged. The typical response time noted is around 84 seconds, which significantly hinders usability.

   The recurring warning during each operation is:
   ```
   [WARNING] - task_type is None, set it to `caption`
   ```
   This warning suggests that `task_type` is not set during initialization and defaults repeatedly on each request.

3. **Model Configuration Warnings**:
   Another consistent warning relates to generation configuration:
   ```
   [INFO|configuration_utils.py:826] Generate config GenerationConfig { "bos_token_id": 50256, "eos_token_id": 50256 }
   ```

Please let me know what system are you using, is it windows linux or mac. I am really interested with starting with the demo, what would be the quickest way to test?

Thanks!

**Comment by xk-huang** [comment]
1. You can start the docker via the host mode: `--network host`. See https://github.com/xk-huang/segment-caption-anything/blob/main/docs/ENV.md
2. The warning told you that you are using the default `caption` model, which you can safely ignore.
3. It is not warning but info, which again you can ignore.

**Comment by xk-huang** [comment]
To run the demo, please read the docs below in order, which are listed in https://github.com/xk-huang/segment-caption-anything/blob/main/README.md：
1. Environment Preparation
Please check [docs/ENV.md](https://github.com/xk-huang/segment-caption-anything/blob/main/docs/ENV.md).

2. Download the weights in Model Zoo
Please check [docs/MODEL_ZOO.md](https://github.com/xk-huang/segment-caption-anything/blob/main/docs/MODEL_ZOO.md)

3. Run Gradio Demo
Please check [docs/DEMO.md](https://github.com/xk-huang/segment-caption-anything/blob/main/docs/DEMO.md)

**Comment by hamzafer** [comment]
Thanks @xk-huang for the detailed reply. I am able to run the demo using Docker on Windows!
But the issue is im only able to get the single word of the object in the image, the demo is not returning the `captions`?
Could you help me to understand how to generate captions instead of just segmentation, because this should be the main task of this repo. I am attaching some test images.
![image](https://github.com/xk-huang/segment-caption-anything/assets/45764331/a464fd44-006f-4add-a62d-6755c48b4d35)
![image](https://github.com/xk-huang/segment-caption-anything/assets/45764331/277ad2df-0f29-4a39-8433-3e30d7ee0c8b)
![image](https://github.com/xk-huang/segment-caption-anything/assets/45764331/20885849-b7da-4bd1-bd44-89bba6965c55)

**Comment by xk-huang** [comment]
It seems that you are using the pretrained model which only predict the class label. Use other models instead.

Thanks.
