### ISSUE TITLE
How to run this repository to get captions for a given image.

### ISSUE THREAD

**Issue by eranga-akva** [xk-huang/segment-caption-anything#9]
I needed to get captions for a given image possibly to a text file using this repository. And I could not run the project with the instructions provided. (I tried running this in Google Colab.)

In Colab what I did was, cloning the repo and then following the  [Usage Documentation](https://github.com/xk-huang/segment-caption-anything/blob/main/docs/USAGE.md) 

First tried the inference instruction in that, but since this path was not there `amlt/train-sca-vg_densecap-081023/gpt2-large/checkpoint-9000` it failed. I do not see amlt in the repo folder.

<img width="1055" alt="Screenshot 2024-07-03 at 17 27 46" src="https://github.com/xk-huang/segment-caption-anything/assets/79952089/c273f14c-a2cb-4284-846b-75640f682d66">

Then I tried the usage part but it complained that some files are missing in `/mnt/onemodel/data_raw/VisualGenome/annotations/` directory.

<img width="1081" alt="Screenshot 2024-07-03 at 17 28 47" src="https://github.com/xk-huang/segment-caption-anything/assets/79952089/e6896ad4-834c-4233-a2fb-0e72da9ec8af">

Is there an order that I should execute commands or am I doing something wrong here?

**I would grately appreciate if someone could advice me on how to achieve the required functionality. Here is the [Colab gist ](https://gist.github.com/eranga-akva/f051a7b89af4642801effd4dbf67673c)**

Additionally I was able to run the Gradio demo and get a public link by setting the` share=True` in `scripts/app/sca_app.py`.  But when uploaded an image in anything mode it returns me an error (following image) as well with nothing on Colab console.

<img width="892" alt="Screenshot 2024-07-03 at 17 22 05" src="https://github.com/xk-huang/segment-caption-anything/assets/79952089/8c4a2789-7f33-4b62-a2e2-7958d85496c5">

**Comment by xk-huang** [comment]
Hi @eranga-akva ,

`USAGE` doc is for training and evaluation on the benchmark.

If you only want to run inference on your images and get the predicted texts into a given file, you would have to write some code.

Or you can try the demo.

See https://github.com/xk-huang/segment-caption-anything/issues/6

**Comment by eranga-akva** [comment]
Hi @xk-huang  thanks for the reply. Also could I know what are the system requirements (like memory) to run the demo project? Seems it is the processing slowness that gives me the error above that I have mentioned when running the demo in Gradio.

**Comment by xk-huang** [comment]
16GB memory is enough for fp16 inference.
Since there is no optimization for the LM, the speed is quite slow.
Using A100, it takes seconds to inference one region and about half a minute to run "anything mode".
It would be easy to boost the inference speed with vLLM.

(I think low-bit quantization would help but I have no idea how it impacts the caption ability.)

**Comment by eranga-akva** [comment]
Okay thanks.
